### ISSUE TITLE
Developer Setup Script Versioning Issue

### ISSUE THREAD

**Issue by schutzenjager** [RavenousMechanism/RavenousMechanism#32]
The developer setup script incorrectly attempts to validate the Windows OS version for non Windows 10 machines.

In Windows OS versions prior to Windows 10, the release version (major and minor) did not correlate directly with the product name, so for instance:

Windows 2000: NT 5.0
Windows XP: NT 5.1
Window Vista: NT 6.0
Window 7: NT 6.1
Windows 8: NT 6.2
Windows 8.1: NT 6.3
Windows 10: NT 10.0

Additionally, should we want to extract any additional system information for setup, we could use 'systeminfo' on Windows platforms (this will also provide the proper formatted product name rather than us hardcoding it)

**Comment by GodwinneLorayne** [comment]
Moved to Taiga
